### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by LauUng** [openep/openep-core#15]
Seems like quite a few dependencies are missing for external users:
- triarea
- tricentroid
- lineLenght
- writeTriRep2VTK
- plotsphere
- nleo
- ...

Also, it would be nice if the demo was executable without having to change the path to the example file to load by loading relative paths.

**Comment by noelfitzpatrick** [comment]
Had trouble running the demo, specifically because lineLenght can't be found (only displays CV map). Is lineLenght() from a custom module or is it available somewhere? Thanks. Noel.

**Comment by drsewilliams** [comment]
Thanks Lau and Noel, I’ll make sure these dependencies are added and update the example as suggested.

**Comment by drsewilliams** [comment]
Hi Noel, hi Lau, I *think* the dependencies are added now. I will do some more checking but if you want to have a look too and let me know if you hit any other problems I will add any remaining files. I'll keep this issue open for now.

**Comment by drsewilliams** [comment]
Issue closed prior to release v1.0.0
