### ISSUE TITLE
What is the effect of using CARTO's dynamic reference vs. a set reference?

### ISSUE THREAD

**Issue by Jsalas424** [openep/openep-core#75]
Hi team,

During data import, we select a reference signal for the map. What is the effect of using dynamic reference (which looks at V1-V6) on your data processing method? Concurrently, what happens if I just select V1 on import?

**Comment by drsewilliams** [comment]
Hi, thanks for the enquiry

The effect is only to set which reference signal to store. We haven't tested this in a real dataset using dynamic reference, however, I think the expected functionality will be:

- the reference signal which is stored will be the reference that you chose, e.g. V1 as per your example
- the annotations will (/should, I believe) still be the annotations which are calculated based on the dynamic reference.

Hope that helps, happy to look at a dataset if it helps.

**Comment by Jsalas424** [comment]
Dr. Williams, If it would help, I can share a case that was mapped with dynamic reference.  -JS  From: Steven Williams ***@***.***>Date: Friday, September 16, 2022 at 9:34 AMTo: openep/openep-core ***@***.***>Cc: Jsalas424 ***@***.***>, Author ***@***.***>Subject: Re: [openep/openep-core] What is the effect of using CARTO's dynamic reference vs. a set reference? (Issue #75)Hi, thanks for the enquiryThe effect is only to set which reference signal to store. We haven't tested this in a real dataset using dynamic reference, however, I think the expected functionality will be:the reference signal which is stored will be the reference that you chose, e.g. V1 as per your examplethe annotations will (/should, I believe) still be the annotations which are calculated based on the dynamic reference.Hope that helps, happy to look at a dataset if it helps.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
